#!/usr/bin/env bash
# build-kit.sh — assemble the SERVED kit tree (v1/) from the masters (B-485).
#   Masters born in the kit live in ./src (sonor-slot-grid.js …). Masters that still live at the workspace root
#   (sonor-icons.js, sonor-takeoffs-modal.js, sonor-project-bar.js, sonor-wq-bar.js, data/sonor-components.css,
#   Branding - CORE/dist/brand.css) are pulled from ../ until step 2 of the cohesion plan moves them in here.
#   Output: v1/manifest.json · v1/kit.css (brand tokens + components) · v1/modules/*.js
#   Usage: bash build-kit.sh   (idempotent; run before committing sonor-kit)
set -euo pipefail
cd "$(dirname "$0")"
ROOT=".."; OUT="v1"; VERSION="$(cat VERSION)"   # v1/ at the repo ROOT so Pages serves https://sonorltd.github.io/sonor-kit/v1/kit.js
mkdir -p "$OUT/modules"
pull() { local src="$1" dst="$2"; if [[ -f "src/$src" ]]; then cp "src/$src" "$dst"; elif [[ -f "$ROOT/$src" ]]; then cp "$ROOT/$src" "$dst"; else echo "missing master: $src" >&2; exit 1; fi; }
{ echo "/* Sonor Kit v$VERSION — brand tokens + components, served in the sonor-kit layer. Generated by build-kit.sh $(date -u +%Y-%m-%dT%H:%MZ) */"; cat "$ROOT/Branding - CORE/dist/brand.css"; echo; cat "$ROOT/data/sonor-components.css"; } > "$OUT/kit.css"
MODULES=(sonor-theme.js sonor-icons.js sonor-takeoffs-modal.js sonor-project-bar.js sonor-wq-bar.js sonor-slot-grid.js sonor-rack-calc.js sonor-sortable.js)
for m in "${MODULES[@]}"; do pull "$m" "$OUT/modules/$m"; done
# catalogue local copies (so ../src/* references work when served from the repo)
for m in sonor-icons.js; do [[ -f "src/$m" ]] || cp "$ROOT/$m" "src/$m"; done
cp "$ROOT/data/sonor-components.css" src/sonor-components.css; cp "$ROOT/Branding - CORE/dist/brand.css" src/brand.css
node -e "
const fs=require('fs'); const mods=process.argv.slice(1); fs.writeFileSync('$OUT/manifest.json', JSON.stringify({ version: '$VERSION', built: new Date().toISOString(), modules: mods, css: 'kit.css' }, null, 2));" "${MODULES[@]}"
echo "kit v$VERSION → $OUT ($(ls "$OUT/modules" | wc -l | tr -d ' ') modules)"
